apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backenddb
    spec:
      containers:
        - name: backenddb
          image: jyothihomedocker/backenddb:latest
          ports:
            - containerPort: 5432
